In [1]:
from sympy.physics.units import temperature

from avito.constants import SPLIT_MARKERS
from avito.prompts import shouldSplitInstructionPrompt, shouldSplitPromptWithRAG
from common.mistral import call_mistral, MistralCallConfig
from common.logger import AVITO_SHOULD_SPLIT_LOGGER as logger

from langgraph.graph import StateGraph
from langgraph.graph import START, END
from typing import *

import re

from pydantic import BaseModel

from common.paths import get_avito_data_dpath
import pandas as pd
import ast

In [2]:
data_dpath = get_avito_data_dpath()

In [3]:
mc_map_fpath = data_dpath / "rnc_mic_key_phrases.csv"
mc_map_df = pd.read_csv(mc_map_fpath)

mc_map = {
    row["mcId"]: row["mcTitle"]
    for _, row in mc_map_df.iterrows()
}
keyphrases = [string.split("; ") for string in mc_map_df["keyPhrases"].tolist()]

print(keyphrases[:5])
print(mc_map)
mc_map_df.head()

[['ремонт под ключ', 'комплексный ремонт', 'полный ремонт квартиры', 'ремонт квартиры под ключ', 'ремонт дома под ключ', 'ремонт коттеджа под ключ', 'капитальный ремонт под ключ', 'косметический ремонт под ключ', 'комплексная отделка', 'полная отделка квартиры', 'ремонт помещений под ключ', 'весь цикл ремонта', 'ремонт от демонтажа до чистовой', 'ремонт с нуля под ключ', 'ремонт вторички под ключ', 'ремонт новостройки под ключ', 'ремонт офиса под ключ', 'ремонт комнаты под ключ', 'ремонт кухни под ключ', 'ремонт ванной под ключ', 'комплекс работ по ремонту', 'ремонт с материалами', 'ремонт без посредников под ключ', 'ремонт с дизайн проектом', 'ремонт с черновой и чистовой отделкой', 'сдаем объект под ключ', 'ведем ремонт полностью', 'выполняем весь комплекс работ', 'берем объект целиком', 'ремонт под сдачу', 'ремонт для проживания под ключ', 'отделка под ключ', 'полное обновление квартиры', 'ремонт жилья под ключ', 'комплексный ремонт квартиры', 'комплексный ремонт дома', 'ремонт под ключ с гарантией', 'ремонт квартиры полностью', 'полный цикл отделочных работ', 'генподряд на ремонт', 'ремонт помещения целиком', 'комплексная переделка квартиры', 'ремонт с инженерией и отделкой', 'комплексный ремонт санузла и кухни', 'ремонт объекта полностью'], ['сантехника', 'сантехнические работы', 'услуги сантехника', 'вызов сантехника', 'разводка труб', 'разводка воды', 'разводка канализации', 'монтаж водоснабжения', 'монтаж канализации', 'замена труб', 'пайка труб', 'полипропиленовые трубы', 'металлопластиковые трубы', 'прокладка труб', 'перенос труб', 'установка сантехники', 'монтаж сантехники', 'подключение сантехники', 'установка унитаза', 'установка инсталляции', 'монтаж инсталляции', 'установка раковины', 'установка мойки', 'установка ванны', 'установка душевой кабины', 'установка душевого уголка', 'установка смесителя', 'замена смесителя', 'установка полотенцесушителя', 'замена полотенцесушителя', 'подключение стиральной машины', 'подключение посудомоечной машины', 'монтаж бойлера', 'установка водонагревателя', 'ремонт сантехники', 'замена сифона', 'установка фильтров воды', 'монтаж коллектора воды', 'опрессовка труб', 'устранение протечки', 'ремонт унитаза', 'замена стояка', 'разводка в санузле', 'сборка сантехнического шкафа', 'замена арматуры бачка'], ['электрика', 'электромонтажные работы', 'услуги электрика', 'вызов электрика', 'замена проводки', 'полная замена проводки', 'черновая электрика', 'монтаж электрики', 'разводка электрики', 'прокладка кабеля', 'штробление под проводку', 'перенос розеток', 'установка розеток', 'замена розеток', 'установка выключателей', 'замена выключателей', 'монтаж светильников', 'подключение светильников', 'установка люстры', 'подключение люстры', 'монтаж бра', 'монтаж трековых светильников', 'сборка электрощита', 'монтаж щита', 'замена автомата', 'установка автоматов', 'замена УЗО', 'подключение варочной панели', 'подключение духового шкафа', 'подключение электроплиты', 'вывод под кондиционер', 'вывод кабеля под технику', 'монтаж слаботочки', 'интернет кабель', 'тв кабель', 'подсветка потолка', 'монтаж теплого пола электрического', 'поиск неисправности электрики', 'ремонт электрики', 'диагностика электрики', 'заземление', 'монтаж распределительных коробок', 'сборка схемы освещения', 'электрика в новостройке', 'электрика в квартире', 'электрика под ключ'], ['натяжные потолки', 'монтаж натяжных потолков', 'установка натяжных потолков', 'потолки ПВХ', 'тканевые потолки', 'сатиновые потолки', 'матовые потолки', 'глянцевые потолки', 'многоуровневые потолки', 'теневой потолок', 'парящий потолок', 'натяжной потолок с подсветкой', 'потолок со световыми линиями', 'потолок с треками', 'монтаж профиля потолка', 'установка багета', 'обход труб на потолке', 'слив воды с потолка', 'ремонт натяжного потолка', 'замена полотна потолка', 'перетяжка потолка', 'демонтаж натяжного потолка', 'установка точечных светильников в потолок', 'врезка светильников', 'обход карниза', 'скрытый карниз в потолке', 'ниша под шторы', 'фотопечать на потолке', 'потолок в ванной', 'потолок на кухне', 'потолок в комнате', 'потолок в коридоре', 'натяжной потолок под ключ', 'монтаж потолка за 1 день', 'еврокраб потолок', 'контурная подсветка потолка', 'монтаж закладных под светильники', 'установка вентиляционных решеток в потолок', 'натяжной потолок после залива', 'устранение пореза потолка', 'спайка полотен', 'бесщелевой потолок', 'резной потолок', 'световой потолок', 'монтаж потолка в новостройке'], ['укладка плитки', 'плиточные работы', 'плиточник', 'услуги плиточника', 'укладка керамогранита', 'укладка кафеля', 'укладка плитки на пол', 'укладка плитки на стены', 'облицовка плиткой', 'облицовка санузла', 'фартук из плитки', 'плитка на кухне', 'плитка в ванной', 'плитка в туалете', 'укладка мозаики', 'запил плитки под 45', 'резка плитки', 'сверление плитки', 'затирка швов', 'эпоксидная затирка', 'выравнивание стен под плитку', 'подготовка пола под плитку', 'укладка крупноформатной плитки', 'укладка плитки 120х60', 'укладка керамогранита 60х60', 'укладка плитки елочкой', 'декоративная раскладка плитки', 'монтаж теплого пола под плитку', 'демонтаж старой плитки', 'перекладка плитки', 'ремонт плиточного покрытия', 'облицовка фартука', 'облицовка душевой', 'укладка плитки на балконе', 'укладка клинкера', 'облицовка ступеней плиткой', 'плитка на лестнице', 'плитка по диагонали', 'установка люков под плитку', 'формирование коробов под плитку', 'гидроизоляция под плитку', 'подрезка керамогранита', 'укладка керамической плитки', 'облицовка пола керамогранитом', 'плиточные работы под ключ']]
{101: 'Ремонт квартир и домов под ключ', 102: 'Сантехника', 103: 'Электрика', 104: 'Натяжные потолки', 105: 'Укладка плитки', 106: 'Поклейка обоев', 107: 'Малярные работы', 108: 'Штукатурные работы', 109: 'Напольные покрытия', 110: 'Гипсокартон', 111: 'Демонтажные работы'}

,mcId,mcTitle,keyPhrases,description
0,101,Ремонт квартир и домов под ключ,ремонт под ключ; комплексный ремонт; полный ре...,Комплексный ремонт объекта целиком
1,102,Сантехника,сантехника; сантехнические работы; услуги сант...,Сантехнические работы
2,103,Электрика,электрика; электромонтажные работы; услуги эле...,Электромонтажные работы
3,104,Натяжные потолки,натяжные потолки; монтаж натяжных потолков; ус...,Монтаж и обслуживание натяжных потолков
4,105,Укладка плитки,укладка плитки; плиточные работы; плиточник; у...,Плиточные работы

In [4]:
data_fpath = data_dpath / "rnc_dataset_markup.json"
data_df = pd.read_json(data_fpath)
data_df["targetSplitMcIds"] = data_df["targetSplitMcIds"].apply(ast.literal_eval)
data_df["targetSplitMcTitles"] = data_df["targetSplitMcIds"].apply(lambda mc_ids: [mc_map[mc_id] for mc_id in mc_ids])



def clean_description(text: str) -> str:
    # Оставляем только кириллицу и обычные пробелы
    text = re.sub(r'[^а-яА-ЯёЁ ]', ' ', text)
    # Схлопываем множественные пробелы
    text = re.sub(r' +', ' ', text)
    return text.strip()

data_df["description"] = data_df["description"].apply(clean_description)

from sklearn.model_selection import train_test_split
data_df, val_df = train_test_split(data_df, test_size=0.2, random_state=42)

data_df.head()

,itemId,sourceMcId,sourceMcTitle,description,targetDetectedMcIds,targetSplitMcIds,shouldSplit,caseType,split,targetSplitMcTitles
1125,1001139,101,Ремонт квартир и домов под ключ,Отделка под ключ косметический ремонт помощь в...,[],[],False,no_other_microcategories_detected,NaN,[]
1767,1001787,101,Ремонт квартир и домов под ключ,Уважаемые дамы и господа предлагаем услуги рем...,"[102, 103, 104, 108]",[],False,other_microcategories_detected_but_not_split,NaN,[]
756,1000769,101,Ремонт квартир и домов под ключ,Произведем монтаж натяжного потолка любой слож...,[104],[104],True,split,NaN,[Натяжные потолки]
2471,1002492,101,Ремонт квартир и домов под ключ,Все виды внутри отделочных работ,[],[],False,no_other_microcategories_detected,NaN,[]
1565,1001585,101,Ремонт квартир и домов под ключ,Хотите обновить интерьер своей квартиры но не ...,"[102, 103, 104, 111]",[],False,other_microcategories_detected_but_not_split,NaN,[]

In [10]:
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import SentenceTransformerEmbeddings

embedding_model = SentenceTransformerEmbeddings(model_name="sergeyzh/rubert-mini-frida")
try:
        vectorstore = Chroma(
        embedding_function=embedding_model,
        collection_name="avito_descriptions",
    )
except Exception as e:
    logger.warning(f"Не удалось загрузить существующий векторный стор: {e}")
    vectorstore = Chroma.from_texts(
        texts=data_df["description"].tolist(),
        embedding=embedding_model,
        collection_name="avito_descriptions",
    )
retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

# save vectorstore
vectorstore.persist()

def get_balanced_top_k(desc: str, k: int = 6) -> list:
    results = retriever.invoke(desc, k=20)
    finded_texts = [r.page_content for r in results if r.page_content != desc]

    true_examples = [
        t for t in finded_texts
        if data_df.loc[data_df["description"] == t, "shouldSplit"].values[0]
    ]
    false_examples = [
        t for t in finded_texts
        if not data_df.loc[data_df["description"] == t, "shouldSplit"].values[0]
    ]

    # берём поровну
    half = k // 2
    balanced = true_examples[:half] + false_examples[:half]

    result = []
    for text in balanced:
        cats = data_df.loc[data_df["description"] == text, "targetSplitMcTitles"].values[0]
        verdict = data_df.loc[data_df["description"] == text, "shouldSplit"].values[0]
        result.append((text, verdict, cats))

    return result

Default prompt name is set to 'Classification'. This prompt will be applied to all `encode()` calls, except if `encode()` is called with `prompt` or `prompt_name` parameters.

In [11]:
# utils, nodes, States


def keywords_pre_filter(state: RunState) -> RunState:
    desc = state.description

    split_words_count = 0
    for word in SPLIT_MARKERS:
        if word in desc:
            split_words_count += 1
    split_markers_flag = split_words_count > 0

    # keyphrases
    keyphrases_vec = [0] * len(keyphrases)
    for idx, keyphrase_list in enumerate(keyphrases):
        for keyphrase in keyphrase_list:
            if keyphrase in desc:
                keyphrases_vec[idx] = 1
                break

    if sum(keyphrases_vec) > 1:
        keyphrases_flag = True
    else:
        keyphrases_flag = False

    if split_markers_flag or keyphrases_flag:
        state.shouldSplit = True
    else:
        state.shouldSplit = False

    return state

# example
str_ex = """
бригада мастеров со стажем более 20 лет выполним внутренние отделки домов, квартир офисы И. Т. Д,работа под ключ или же как вам удобно, Шпаклëвка под обои, под покраску,покраска, Штукатурка ,падуги гипсовые, пластиковые, обои,кафель, отопления,ламинат,И.Т.Д, также выполним фасадные работы, утепление пеноплексом, облицовку природным камнем, И. Т. Д. работаем по местным ценам, делаем скидку на каждый вид работы индивидуальный подход к каждому виду работы ,качество и своевременное сдача объекта гарантируем если не возникнет внеплановая ситуация, помощь в подборе материалов вместе с заказчиком, бригада без вредных привычек,работаем полный  рабочий день от выходного до выходного,инструментами обеспечены полностью,пишите. Звоните.
"""
state = RunState(description=str_ex)
state.description = clean_description(state.description)
state = keywords_pre_filter(state)

retriever_results = retriever.invoke(state.description)

finded_texts = [item.page_content for item in retriever_results]
finded_categories = [data_df.loc[data_df["description"] == text, "targetSplitMcTitles"].values[0] for text in finded_texts]
finded_verdicts = [data_df.loc[data_df["description"] == text, "shouldSplit"].values[0] for text in finded_texts]

top_k = [(text, verdict, categories) for text, verdict, categories in zip(finded_texts, finded_verdicts, finded_categories)]

prompt = shouldSplitPromptWithRAG(
    desc=state.description,
    top_k=top_k
)

print(prompt)

Похожие объявления из базы:


Объявление для классификации:
бригада мастеров со стажем более лет выполним внутренние отделки домов квартир офисы И Т Д работа под ключ или же как вам удобно Шпакл вка под обои под покраску покраска Штукатурка падуги гипсовые пластиковые обои кафель отопления ламинат И Т Д также выполним фасадные работы утепление пеноплексом облицовку природным камнем И Т Д работаем по местным ценам делаем скидку на каждый вид работы индивидуальный подход к каждому виду работы качество и своевременное сдача объекта гарантируем если не возникнет внеплановая ситуация помощь в подборе материалов вместе с заказчиком бригада без вредных привычек работаем полный рабочий день от выходного до выходного инструментами обеспечены полностью пишите Звоните

Нужно ли выделять отдельные микрокатегории?

In [7]:
mistral_config = MistralCallConfig(
     models_list=["mistral-medium-latest"]
)
response = call_mistral(
    mistral_config,
    messages= [
        {
            "role": "system",
            "content": shouldSplitInstructionPrompt
        },
        {
            "role": "user",
            "content": prompt
        },
    ],
    reasoning_effort="hard"

)
print(response)

2026-04-08 16:57:17,696 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:57:17,696 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:57:17,696 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 16:57:17,885 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:57:17,885 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:57:17,895 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:57:18,414 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:57:18,416 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:57:18,417 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest

False

In [13]:
from tqdm.auto import tqdm

subsample_df = val_df.sample(50, random_state=43)
preds = []
for _, row in tqdm(subsample_df.iterrows(), total=len(subsample_df)):
    state = RunState(description=row["description"])
    state.description = clean_description(state.description)
    state = keywords_pre_filter(state)

    retriever_results = retriever.invoke(state.description)

    finded_texts = [item.page_content for item in retriever_results]
    finded_texts_without_gt = [text for text in finded_texts if text != state.description]

    finded_categories = [data_df.loc[data_df["description"] == text, "targetSplitMcTitles"].values[0] for text in finded_texts]
    finded_verdicts = [data_df.loc[data_df["description"] == text, "shouldSplit"].values[0] for text in finded_texts]

    top_k = [(text, verdict, categories) for text, verdict, categories in zip(finded_texts, finded_verdicts, finded_categories)]

    prompt = shouldSplitPromptWithRAG(
        desc=state.description,
        top_k=top_k
    )

    mistral_config = MistralCallConfig(
         models_list=["mistral-medium-latest"]
    )
    response = call_mistral(
        mistral_config,
        messages= [
            {
                "role": "system",
                "content": shouldSplitInstructionPrompt
            },
            {
                "role": "user",
                "content": prompt
            },
        ],
        reasoning_effort="hard"

    )
    preds.append("True" in response)

subsample_df["mistral_rag_prediction"] = preds

print(f"Accuracy: {(subsample_df['shouldSplit'] == subsample_df['mistral_rag_prediction']).mean():.4f}")
subsample_df[["description", "shouldSplit", "mistral_rag_prediction"]] # noqa

  0%|          | 0/50 [00:00<?, ?it/s]

2026-04-08 16:44:07,536 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:07,538 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:07,542 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:07,574 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:07,576 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:07,580 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:19,793 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:19,796 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:19,797 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:19,825 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:19,827 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:19,831 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:19,863 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:19,865 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:19,868 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:20,451 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:20,453 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:20,455 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:20,479 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:20,482 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:20,485 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:20,511 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:20,513 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:20,516 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:24,414 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:24,416 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:24,417 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:24,497 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:24,499 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:24,502 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:24,529 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:24,532 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:24,535 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:25,743 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:25,744 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:25,746 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:25,771 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:25,773 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:25,777 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:25,807 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:25,809 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:25,811 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:26,400 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:26,402 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:26,403 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:26,425 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:26,427 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:26,430 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:26,460 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:26,462 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:26,472 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:27,935 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:27,937 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:27,938 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:27,968 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:27,970 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:27,973 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:28,003 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:28,004 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:28,008 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:28,595 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:28,597 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:28,599 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:28,622 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:28,624 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:28,627 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:28,661 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:28,663 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:28,667 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:29,374 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:29,374 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:29,379 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:29,421 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:29,423 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:29,426 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:29,457 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:29,459 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:29,462 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:30,195 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:30,197 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:30,198 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:30,220 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:30,223 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:30,226 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:30,256 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:30,258 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:30,261 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:30,824 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:30,825 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:30,827 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:30,861 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:30,863 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:30,867 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:30,897 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:30,899 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:30,902 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:31,443 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:31,445 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:31,447 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:31,484 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:31,486 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:31,490 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:31,521 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:31,523 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:31,527 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:32,187 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:32,189 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:32,191 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:32,213 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:32,216 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:32,219 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:32,246 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:32,249 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:32,251 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:32,674 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:32,677 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:32,678 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:32,703 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:32,706 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:32,709 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:32,741 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:32,743 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:32,746 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:33,779 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:33,781 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:33,782 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:33,803 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:33,805 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:33,808 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:33,838 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:33,840 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:33,843 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:35,974 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:35,976 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:35,978 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:36,025 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:36,027 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:36,030 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:36,058 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:36,060 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:36,063 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:37,812 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:37,813 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:37,815 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:37,838 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:37,841 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:37,843 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:37,876 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:37,877 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:37,880 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:38,273 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:38,275 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:38,277 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:38,299 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:38,300 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:38,304 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:38,336 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:38,338 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:38,340 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:40,031 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:40,033 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:40,034 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:40,062 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:40,063 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:40,067 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:40,099 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:40,102 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:40,106 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:40,577 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 16:44:40,579 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:40,581 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:40,653 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:40,655 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:40,659 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:40,686 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:40,688 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 16:44:40,690 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 16:44:42,246 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 16:44:42,247 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 16:44:42,249 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 16:44:42,276 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 16:44:42,279 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort']
2026-04-08 16:44:42,282 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 3/21
2026-04-08 16:44:42,312 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 16:44:42,315 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1

Accuracy: 0.5400

,description,shouldSplit,mistral_rag_prediction
1025,Ремонт квартир домов любой сложности Монтаж де...,False,True
1888,бригада строителей выполняем все виды ремонта ...,False,True
1005,Отделка домов и квартир Штукатурка Шпаклевка П...,False,True
2397,Здравствуйте Меня зовут Александр я инженер ст...,False,True
210,Делаю все виды отделочных работ,False,False
1362,Плитка обои ламинат и прочее Где надо оштукату...,False,True
1034,Предоставляю услуги мастера плотника универсал...,False,True
1709,Самая низкая цена по Краснодару и Краснодарско...,False,False
1956,Мы небольшая частная бригада по ремонту кварти...,False,True
1790,Ремонт квартир и отделка любой сложности косме...,False,False
1646,П дл г ет вам широкий комплекс услуг п отделке...,False,False
1525,Ремонт квартир под ключ т м с гарантией по дог...,False,False
1814,Ремонт квартир домов коммерческих зданий Гаран...,False,False
679,Строительная бригада Все виды ремонтно строите...,False,False
1658,выполняем любые виды строительных работ,False,False
1924,Комплексные услуги ремонта и отделки под ключ ...,True,True
2275,Любые виды внутренней и наружной отделки Покле...,False,True
1511,ЗДРАВСТВУЙТЕ мы выполняем следующие виды работ...,True,True
2077,Весь спектр отделочных работ под ключ Професси...,False,True
1418,РЕМОНТ КВАРТИР ОТ ЧАСТНОЙ БРИГАДЫ Д рю т плый ...,False,False
610,Здравствуйте меня зовут Николай Я частный маст...,False,True
1374,Ищу работу по ремонту квартир шпатлёвка обой п...,False,True
862,Мы занимаемся ремонтом и демонтажом во вторичк...,True,False
402,Построили дом купили квартиру или арендовали о...,False,False
2168,Выполним покраску фасадов металлоконструкций п...,False,True
2426,Делаем качественный ремонт квартир и офисов Вс...,False,False
2312,Выполнение абсолютно любых видов работ,False,False
29,Бригада выполнит работу любой сложности по рек...,True,True
1607,Здравствуйте Указана цена за квадратный метр п...,True,True
1302,Мы опытные мастера по ремонту квартир с высоко...,False,False
141,Отделочные работы квартир частных домов магази...,False,True
2161,Ремонт квартир и домов под ключ Москва и МО Бр...,False,True
2159,Выполняем работы Отделочные Штукатурка Шпатлёв...,False,True
2444,Предоставляем ремонт квартир любой сложности п...,False,False
693,Оказываем услуги по ремонту квартир строительс...,False,False
1789,Ремонт квартир домов и офисов под ключ Штукату...,True,True
2379,Укладка плитки ремонт с у под ключ,True,True
1334,Предлагаем услуги по ремонту квартир любой сло...,False,True
916,Ремонт квартир под ключ с гарантией Выполняю р...,False,True
2359,Зд в твуйте м ня з вут Валерий я и моя бригада...,False,True
1684,Здравствуйте Все фото в моем профиле реальные ...,True,True
1960,Все виды отделочных работ Демонтаж Штукатурка ...,False,True
2303,Наша компания оказывает услуги по профессионал...,False,False
2282,Обмеры в Ульяновске Что вы получаете при станд...,True,False
2060,Профессиональная установка межкомнатных дверей...,True,True
2143,Покраска кафельной плитки Быстрое исполнение П...,False,True
471,Выполним отделочные работы Гипсокартон стены п...,False,True
485,Звоните договоримся о встрече и всё обсудим,False,False
482,Здравствуйте переходите на сайт ВКонтакте там ...,False,False
1159,Устанавливаем натяжные потолки любой сложности...,True,True

In [18]:
class RunState(BaseModel):
    description: str
    shouldSplit: bool = False
    embedding: Optional[list[float]] = None
    top_k_examples: Optional[list[tuple[str, bool, list[str]]]] = None
    drafts: list[str] = []

    last_node: Optional[str] = None
    metadata: dict[Any, Any] = {}

from dataclasses import dataclass

class ShouldSplitGraph:
    def __init__(self):
        self.verbose = True

        @dataclass
        class nodes:
            clean = "clean"
            pre_filter = "pre_filter"
            pre_filter_exit = "pre_filter_exit"
            rag_split = "rag_split"
            llm_exit = "llm_exit"
            drafts = "drafts"
            drafts_exit = "drafts_exit"

        self.nodes = nodes

        builder = StateGraph(RunState)

        builder.add_node("clean", self.clean_description_node)
        builder.add_node("pre_filter", self.keywords_pre_filter_logged)
        builder.add_node("pre_filter_exit", self.pre_filter_exit)

        builder.add_node("rag_split", self.rag_should_split)
        builder.add_node("llm_exit", self.llm_exit)

        builder.add_node("drafts", self.generate_drafts)
        builder.add_node("drafts_exit", self.drafts_exit)

        builder.set_entry_point("clean")
        builder.add_edge("clean", "pre_filter")

        builder.add_conditional_edges(
            "pre_filter",
            lambda state: "rag_split" if state.shouldSplit else "pre_filter_exit"
        )

        builder.add_conditional_edges(
            "rag_split",
            self.should_split_router,
            {"split": "drafts", END: "llm_exit"}
        )

        builder.add_edge("drafts", "drafts_exit")

        builder.add_edge("pre_filter_exit", END)
        builder.add_edge("llm_exit", END)
        builder.add_edge("drafts_exit", END)

        self.graph = builder.compile()

    def _log(self, msg: str):
        if self.verbose:
            logger.info(msg)

    def clean_description_node(self, state: RunState) -> RunState:
        before = len(state.description)
        state.description = clean_description(state.description)
        after = len(state.description)

        self._log("━" * 50)
        self._log(f"🧹 [clean] {before} → {after} символов")
        return state

    def keywords_pre_filter_logged(self, state: RunState) -> RunState:
        state = keywords_pre_filter(state)

        self._log("━" * 50)
        self._log(f"🔑 [pre_filter] shouldSplit={state.shouldSplit}")
        if not state.shouldSplit:
            self._log("   Ключевые фразы/маркеры не найдены → завершаем на pre_filter")
        else:
            self._log("   Префильтр сработал → идём в RAG/LLM")
        return state

    def pre_filter_exit(self, state: RunState) -> RunState:
        self._log("━" * 50)
        self._log("⛔ [pre_filter_exit] Пайплайн завершён после префильтра")
        return state

    def rag_should_split(self, state: RunState) -> RunState:
        self._log("━" * 50)
        self._log("🔍 [rag_split] СТАРТ")
        self._log(f"   Текст ({len(state.description)} символов): {state.description[:100]}...")

        retriever_results = get_balanced_top_k(state.description, k=6)
        finded_texts = [item.page_content for item in retriever_results]
        finded_texts = [text for text in finded_texts if text != state.description]
        self._log(f"   RAG вернул {len(finded_texts)} кандидатов (без точного совпадения)")

        finded_categories = [
            data_df.loc[data_df["description"] == text, "targetSplitMcTitles"].values[0]
            for text in finded_texts
        ]
        finded_verdicts = [
            data_df.loc[data_df["description"] == text, "shouldSplit"].values[0]
            for text in finded_texts
        ]

        top_k = list(zip(finded_texts, finded_verdicts, finded_categories))

        self._log("   Топ-k примеры:")
        for i, (text, verdict, cats) in enumerate(top_k):
            self._log(f"   [{i+1}] shouldSplit={verdict} | кат={cats} | текст: {text[:60]}...")

        prompt = shouldSplitPromptWithRAG(desc=state.description, top_k=top_k)

        self._log("   Отправляем запрос в Mistral...")
        response = call_mistral(
            MistralCallConfig(models_list=["mistral-medium-latest"]),
            messages=[
                {"role": "system", "content": shouldSplitInstructionPrompt},
                {"role": "user", "content": prompt},
            ],
            reasoning_effort="hard",
            temperature=0.0,
        )

        decision = "True" in str(response)
        self._log(f"   Ответ модели: {str(response)[:100]}")
        self._log(f"   Решение: {'✅ SPLIT' if decision else '❌ NO SPLIT'}")

        state.shouldSplit = decision
        return state

    def should_split_router(self, state: RunState) -> str:
        route = "split" if state.shouldSplit else END
        self._log(f"🔀 [router] → {route}")
        return route

    def llm_exit(self, state: RunState) -> RunState:
        self._log("━" * 50)
        self._log("⛔ [llm_exit] Пайплайн завершён после LLM")
        self._log(f"   shouldSplit={state.shouldSplit}")
        return state

    def generate_drafts(self, state: RunState) -> RunState:
        self._log("━" * 50)
        self._log("📝 [drafts] СТАРТ — генерация черновиков")
        self._log("📝 [drafts] КОНЕЦ")
        return state

    def drafts_exit(self, state: RunState) -> RunState:
        self._log("━" * 50)
        self._log("✅ [drafts_exit] Пайплайн завершён после drafts")
        return state

    def invoke(self, description: str, verbose: bool = True) -> RunState:
        prev_verbose = self.verbose
        self.verbose = verbose

        try:
            self._log("═" * 50)
            self._log("🚀 [pipeline] СТАРТ")
            self._log(f"   Вход: {description[:100]}...")

            state = RunState(description=description)
            result = self.graph.invoke(state)
            final = RunState(**result)

            self._log("═" * 50)
            self._log(f"🏁 [pipeline] КОНЕЦ | shouldSplit={final.shouldSplit}")
            self._log("═" * 50)

            return final
        finally:
            self.verbose = prev_verbose

pipeline = ShouldSplitGraph()
result = pipeline.invoke(str_ex, verbose=True)
print(result.shouldSplit)

2026-04-08 17:19:02,785 - avito-should-split - INFO - [SHOULD_SPLIT] ══════════════════════════════════════════════════
2026-04-08 17:19:02,787 - avito-should-split - INFO - [SHOULD_SPLIT] 🚀 [pipeline] СТАРТ
2026-04-08 17:19:02,789 - avito-should-split - INFO - [SHOULD_SPLIT]    Вход:
бригада мастеров со стажем более 20 лет выполним внутренние отделки домов, квартир офисы И. Т. Д,ра...
2026-04-08 17:19:02,794 - avito-should-split - INFO - [SHOULD_SPLIT] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2026-04-08 17:19:02,797 - avito-should-split - INFO - [SHOULD_SPLIT] 🧹 [clean] 736 → 707 символов
2026-04-08 17:19:02,800 - avito-should-split - INFO - [SHOULD_SPLIT] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2026-04-08 17:19:02,802 - avito-should-split - INFO - [SHOULD_SPLIT] 🔑 [pre_filter] shouldSplit=False
2026-04-08 17:19:02,805 - avito-should-split - INFO - [SHOULD_SPLIT]    Ключевые фразы/маркеры не найдены → завершаем на pre_filter
2026-04-08 17:19:02,808 - avito-should-split - INFO - [SHOULD_SPLIT] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2026-04-08 17:19:02,810 - avito-should-split - INFO - [SHOULD_SPLIT] ⛔ [pre_filter_exit] Пайплайн завершён после префильтра
2026-04-08 17:19:02,813 - avito-should-split - INFO - [SHOULD_SPLIT] ══════════════════════════════════════════════════
2026-04-08 17:19:02,815 - avito-should-split - INFO - [SHOULD_SPLIT] 🏁 [pipeline] КОНЕЦ | shouldSplit=False
2026-04-08 17:19:02,817 - avito-should-split - INFO - [SHOULD_SPLIT] ══════════════════════════════════════════════════

False

In [13]:
from tqdm.auto import tqdm
val_scores = []
subsample_df = val_df.sample(200, random_state=12)
for _, row in tqdm(subsample_df.iterrows(), total=len(subsample_df)):
    result = pipeline.invoke(row["description"], verbose=False)
    val_scores.append(result.shouldSplit)

subsample_df["pipeline_prediction"] = val_scores
print(f"Pipeline Accuracy: {(subsample_df['shouldSplit'] == subsample_df['pipeline_prediction']).mean():.4f}")
subsample_df[["description", "shouldSplit", "pipeline_prediction"]] # noqa

  0%|          | 0/200 [00:00<?, ?it/s]

2026-04-08 17:09:04,585 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:04,588 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:04,591 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:04,784 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:04,784 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:04,791 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:16,565 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:16,567 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:16,569 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:16,594 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:16,596 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:16,600 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:16,626 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:16,627 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:16,630 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:16,998 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 8 символов
2026-04-08 17:09:16,999 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:17,001 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:17,039 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:17,041 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:17,044 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:17,069 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:17,071 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:17,073 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:17,541 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:17,543 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:17,544 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:17,600 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:17,602 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:17,605 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:17,633 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:17,636 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:17,639 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:18,148 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:18,150 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:18,151 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:18,191 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:18,193 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:18,196 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:18,230 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:18,232 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:18,235 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:19,305 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 161 символов
2026-04-08 17:09:19,307 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:19,308 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:19,328 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:19,330 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:19,334 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:19,367 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:19,370 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:19,372 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:20,403 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 173 символов
2026-04-08 17:09:20,405 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:20,407 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:20,478 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:20,480 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:20,483 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:20,517 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:20,519 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:20,522 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:21,228 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:21,230 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:21,231 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:21,258 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:21,260 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:21,262 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:21,296 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:21,299 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:21,302 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:22,081 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:22,083 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:22,085 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:22,145 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:22,147 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:22,150 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:22,176 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:22,179 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:22,182 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:22,709 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 8 символов
2026-04-08 17:09:22,711 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:22,713 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:22,765 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:22,767 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:22,770 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:22,796 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:22,800 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:22,802 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:23,406 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:23,408 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:23,409 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:23,432 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:23,434 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:23,438 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:23,470 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:23,471 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:23,474 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:24,037 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 32 символов
2026-04-08 17:09:24,039 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:24,041 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:24,070 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:24,072 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:24,075 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:24,105 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:24,107 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:24,110 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:24,435 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 8 символов
2026-04-08 17:09:24,437 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:24,438 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:24,462 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:24,464 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:24,467 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:24,496 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:24,499 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:24,501 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:25,650 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:25,651 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:25,652 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:25,681 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:25,683 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:25,686 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:25,721 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:25,723 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:25,726 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:26,074 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 8 символов
2026-04-08 17:09:26,076 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:26,077 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:26,137 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:26,140 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:26,143 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:26,173 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:26,174 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:26,177 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:26,732 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:26,735 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:26,737 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:27,026 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:27,028 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:27,032 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:27,069 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:27,072 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:27,076 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:27,612 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:27,614 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:27,617 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:27,688 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:27,691 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:27,695 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:27,733 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:27,735 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:27,738 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:28,344 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:28,346 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:28,347 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:28,458 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:28,460 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:28,463 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:28,493 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:28,496 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:28,498 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:29,167 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:29,168 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:29,170 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:29,198 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:29,200 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:29,203 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:29,233 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:29,236 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:29,238 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:29,575 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 17:09:29,577 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:29,578 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:29,596 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:29,597 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 17:09:29,600 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 17:09:29,633 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 17:09:29,635 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 17:09:29,638 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 17:09:30,468 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-08 17:09:30,469 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 17:09:30,471 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest
2026-04-08 17:09:30,588 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 17:09:30,590 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']

Pipeline Accuracy: 0.7700

,description,shouldSplit,pipeline_prediction
1377,Ванные комнаты и сан узлы под ключ Демонтаж пе...,True,False
2054,ремонт квартир качественно плиточные работы и ...,False,False
2084,Профес ион льно недорог и кач ств нн п оизв ду...,False,False
2279,Любые ремонтные работы а так же работы по демо...,False,True
1632,Ремонт любой сложности Качество и гарантия сде...,False,False
...,...,...,...
199,Весь спектр отделочных работ штукатурка шпакле...,True,False
1089,делаем капитальный внутренний ремонт а также м...,True,True
2314,Предлагаю Вам услугу в сфере ремонта квартир д...,True,True
1769,строительные работы,False,False
1844,Выполним качественно следующие виды работ штук...,False,False

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

print(classification_report(subsample_df["shouldSplit"], subsample_df["pipeline_prediction"]))
print("Confusion Matrix:")
print(confusion_matrix(subsample_df["shouldSplit"], subsample_df["pipeline_prediction"]))
print(f"F1 Score: {f1_score(subsample_df['shouldSplit'], subsample_df['pipeline_prediction']):.4f}")

              precision    recall  f1-score   support

       False       0.81      0.93      0.87       159
        True       0.35      0.15      0.21        41

    accuracy                           0.77       200
   macro avg       0.58      0.54      0.54       200
weighted avg       0.72      0.77      0.73       200

Confusion Matrix:
[[148  11]
 [ 35   6]]
F1 Score: 0.2069

In [15]:
# some fp samples

fp_samples = subsample_df[(subsample_df["shouldSplit"] == False) & (subsample_df["pipeline_prediction"] == True)]
for idx, row in fp_samples.iterrows():
    print(f"Описание: {row['description']}")
    print(f"shouldSplit: {row['shouldSplit']} | pipeline_prediction: {row['pipeline_prediction']}")
    print("-" * 80)

Описание: Любые ремонтные работы а так же работы по демонтажу Выравнивание стен Поклейка обоев Покраска Работа с гипсокартоном Укладка плитки Обшивка панелями Возведение стен Стяжка пола Укладка линолеум ламинат кварц винил Установка окон остекление балконов Установка дверей Шпатлевка стен и потолков Сборка разборка мебели Любые Сантехнические работы Возможен выезд за Город Пишите Звоните Также работаем с Юр лицами
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Здравствуйте я Татьяна Работаю сама или с бригадой Мы качественно сделаем косметический ремонт выполним подготовку поклеим обои без швов и пузырей Свою работу любим выполняем все аккуратно с душой дляВас Работаем срочно день в день и по записи Имеем много постоянных клиентов для них вне очереди Работаем без выходных за собой оставляем чистоту и порядок Предоплату не берем Выезд на замер и консультация Бесплатно Варианты оплаты Наличными Переводом на любую банковскую карту Звоните пишите прямо сейчас помогу и проконсультирую по ценам и срокам выполнения работ по шпаклёвки и поклейки обоев в вашей квартире доме офисе Поможем решить вашу проблему с ремонтом и выполним для вас следующие работы Шпаклёвка пол обои грунтовка стен Снятие старых обоев Поклейка обоев без подбора рисунка Поклейка обоев с подбором рисунком Поклейка обоев на флизелиновой основе Поклейка виниловых обоев Наши преимущества Идеально Ровные стены и углы Поклейка обоев без стыков и пузырей Консультация и выезд на замер в день Работаем в удобное для вас время и без выходных Прозрачная смена и демократичные цены оплата поэтапно или после выполнения работ Чистота во время и после выполнения ремонта Выполнение ремонта строго по технологии и по качеству Выезжаем в другие районы Добавляйте объявление в Избранное чтобы не потерять Звоните пишите прямо сейчас обсудим все вопросы и поможем решить вашу проблему с ремонтом
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Ремонт квартир и коттеджей под ключ а также частично штукатурка гипсом плитка обои и т д Электрика сантехника канализационные трубы водопроводные трубы пластиковые окна с большими скидками и установка по госту Подбор строительного материала с хорошими скидками Также натяжные потолки с большими скидками Выезд и консультации бесплатно А также мелкие работы Можно выехать на те объекты которые мы сделали чтобы посмотреть качество работы
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Плиточник ремонт ванной комнаты укладка плитки НАПРЯМУЮ БЕЗ посредников и других халтурщиков Не пьем и не курим Так же занимаемся и РЕМОНТОМ КВАРТИРЫ ПОД КЛЮЧ НАПИШИТЕ или ПОЗВОНИТЕ Рассчитаю стоимость работы за мин Бесплатно проконсультирую по материалам Подскажу как и в каком магазине сэкономить ГАРАНТИЯ качественной работы Много лет занимаемся укладкой плитки Большой опыт отделке санузлов полов Арсенал инструментов За счет этого вы получите КАЧЕСТВО и СПОКОЙСТВИЕ ДЛЯ ВАС Бесплатная консультация по телефону Бесплатная смета онлайн Бесплатный выезд мастера на замер и консультация Бесплатный расчет материалов Возможность закупки и доставки материалов Выполняем ремонт под ключ Укладка керамогранита кафеля Штукатурные работы Сантехнические работы Электрика Запилы углов под выполняем на профессиональном оборудовании монтаж душевого поддона и облицовка плиткой монтаж инсталляции установка унитаза раковины ванны и и тд Выполним РЕМОНТ ванной комнаты под ключ за НЕДЕЛИ Укладка плитки достаточно тяжелая и кропотливая работа поэтому настоятельно рекомендуем обращаться к плиточникам знающим все тонкости и нюансы данной работы Мы даём гарантию до лет СКИДКИ ОТ ОБЪЕМА НАЖМИТЕ на сердечко чтобы добавить это объявление в избранное и всегда быть в курсе о новинках ремонта ЕСЛИ Я НЕ ОТВЕТИЛ ПЕРЕЗВОНЮ ИЛИ ПИШИТЕ НА АВИТО В ЧАТ ПОЗВОНИТЕ или НАПИШИТЕ составлю смету и сделаю предварительный расчёт вашего ремонта уже сейчас ДЛЯ ВАС Гарантия год Сохранение цены и сроков работ по договору Без предоплаты поэтапная оплата ремонта Составляем план и смету в день осмотра Помощь с Закупкой и Доставкой только качественных материалов НАПИШИТЕ в чат прямо сейчас составлю смету и сделаю предварительный расчёт вашего ремонта уже сейчас Возможно Вы искали ремонт квартир ремонт ванной ванная под ключ ремонт санузла укладка плитки укладка керамогранита укладка кафеля плиточник ремонт туалета ремонт ванной и туалета
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Обшивка туалетов и ванны домов квартир с пвх панелью Помощь в выборе материала Адекватные цены Большой опыт работы Так же мелкие строительные работы по дому ленолиум плинтуса пороги гардины работы с гипсакортоном сантехника обои подключение стиральных машин вывоз мусора услуга грузчиков электрика обшивка балкона лоджи и т П Выезд и консультация бесплатно
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Плитка гипсокартон штукатурка электрика сантехника и т д и т п Работаю по Владимиру и области РАБОТАЮ ОДИН
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Профессиональный плиточник Без вредных привычек Качественный комплексный ремонт санузлов Договор на работы с гарантией год Фотографии в объявлении мои работы Реализую любую вашу идею применяя современные технологии качественного ремонта ванных комнат и санузлов в том числе эксклюзивно душевой поддон из керамогранита в строительном исполнении в один уровень с полом точный рез керамогранита с переходом рисунка в том числе крупный формат кнопка инсталляции из керамогранита Энергетик Центральная часть Падун Правый берег Плиточные работы укладка кафельной плитки керамогранита мозаики резка и устройство отверстий плитки заусовка плитки под градусов монтаж скрытых люков заполнение швов цементной силиконовой эпоксидной затиркой Монтаж ванны унитаза инсталляции мебели стиральной машины смесителей гигиенического душа биде Демонтаж старой плитки демонтаж построение сантехкабины Выравнивание стен и полов по маякам Монтаж полотенцесушителя водяной и электрический Монтаж водоснабжения металлопластик пвх медь Монтаж системы канализации Монтаж вентиляции Технические решения Плиточные работы плиточник укладка плитки укладка кафеля укладка керамогранита укладка мозаики укладка кафельной плитки укладка крупноформатной плитки укладка крупноформатного керамогранита ремонт ванной комнаты под ключ ремонт туалета под ключ ремонт ванной комнаты и туалета ремонта сан узла ремонт сан узлов укладка фартука из плитки укладка фартука из керамогранита укладка плитки фартук эпоксидная затирка душ из керамогранита кнопка из керамогранита
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Кафельная плитка Керамогранит все виды работ кафель установка сантехники полипропилен электрика наливной пол перепланировка демонтаж закупка материалов все районы кроме Кировского Красноармейского
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Выполняем абсолютно любые виды работ от мелких услуг муж на час до капитального ремонта квартиры Минимальный вызов р
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Ремонт квартир под ключ с гарантией Выполняем любые виды отделочных работ работаем как по дизайн проекту так и без него Примерная стоимость услуг выравнивание потолков м подготовка стен под любые типы обоев от м демонтаж старых обоев от м поклейка обоев от м поклейка потолочного плинтуса от п м покраска стен м подготовка стен под покраску со стеклохолстом от м декоративная штукатурка от м поклейка и покраска молдингов от п м Точную стоимость рассчитываем на месте исходя из фронта работ Цена ремонта определяется стоимостью материалов сложностью и масштабностью работ обсуждается индивидуально с каждым заказчиком Звоните пишите мы всегда на связи
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Добрый день я мастер плиточных работ с большим опытом работы без вредных привычек Сюда входит стяжка пола выравнивание стен короба разводка сантехники плитка потолок электрика гарантия года
shouldSplit: False | pipeline_prediction: True
--------------------------------------------------------------------------------

In [17]:
positive_samples = subsample_df.loc[subsample_df["shouldSplit"]==True].sample(5)
for idx, row in positive_samples.iterrows():
    print(f"Описание: {row['description']}")
    print(f"shouldSplit: {row['shouldSplit']} | pipeline_prediction: {row['pipeline_prediction']}")
    print("-" * 80)

Описание: БЕЗ ПОСРЕДНИКОВ МАСТЕР строительно монтажных и отделочных работ Ремонт одной рукой КАЧЕСТВО СРОКИ УДАЛЕННО ДЕЛАЮ ВСЁ Звоните всё обсудим и воплотим Фото в профиле моих работ видео по запросу Делаю абсолютно все кроме натяжного потолка и установки кондиционера Современное оборудование и инструмент имеется Скидки на стройматериалы имею в большинстве магазинов Доставлю и закуплю материалы сам предоставлю полный финансовый отчёт ЗВОНИТЕ прямо сейчас сдал очередной объект готов брать новый поэтому объявление актуально Ремонт Новостройка Косметический Эконом Стандарт Капитальный Евроремонт По дизайн проекту или картинке с ваших слов и тд Электрика монтаж проводки установка розеток выключателей люстр освещения подсветки замена проводки Выравнивание Штукатурка стяжка шпатлевка стен и потолка откосы шпатлевка под покраску и обои Стены и пол монтаж перегородок шумоизоляция гипсокартон покраска стен обои дерево вагонка пластик плитка кафель укладка ламината керамогранит кварцвинил паркет Установка окон и дверей откосы Потолки шпатлевка под покраску подвесной дерево и ламинат на потолок потолочный плинтус Сантехника прокладка и подключение к системе всех коммуникаций установка ванны душевой кабины инсталляций замена труб душ раковины унитаз смесители полотенцесушитель водонагреватели Отопительная система установка трассы батареи тёплый пол водяное электрика медь полипропилен инфракрасный Вытежки вентиляция
shouldSplit: True | pipeline_prediction: False
--------------------------------------------------------------------------------
Описание: Ремонт и отделка помещений Домов квартир офисов гаражей и т д Плитка шпаклевка штукатурка кладка демонтаж и устройство перегородок кирпич пеноблок гипсокартон и т д Монтаж гипсоплиты В т ч сложные конструкции Установка окон дверей и т д Электромонтажные работы Монтаж систем видео наблюдения Устройство пола ламинат линолеум стяжка плитка Устройство потолков выравнивание монтаж из гипсоплиты любой сложности Сантехнические работы Водопровод отопление канализация Теплый пол монтаж монтаж в существующей стяжке подключение
shouldSplit: True | pipeline_prediction: True
--------------------------------------------------------------------------------
Описание: Профессиональная установка межкомнатных дверей любой сложности и плинтуса мдф установка дверей разных типов моделей производителей обрамление проемов врезка скрытых петель монтаж плинтуса мдф Работаю в городах Обнинск Малоярославец Балабаново Все работы производятся профессиональным инструментом установка двери руб Врезка замка или защелки установка бабочек или врезка карточных петель шт установка ручки и наличника с х сторон установка добора руб на одну дверь ширина до мм монтаж плинтуса мдф руб погонный метр ширина плинтуса до мм запил углов врезка скрытых петель руб петля Цены действительны при установке от х и более дверей
shouldSplit: True | pipeline_prediction: False
--------------------------------------------------------------------------------
Описание: Р монт и отд лка кв ртир коттеджей фис в и други помещ ний под ключ или частично виды монтно отдел чны аб т т экон м д п емиум кла са П мощ п и покупке и до т вки ст оит льных отдел чны мат и л в д кв рти заказчика пыт р боты б л лет честв и ки гарантируем Наши услуги Демонтаж перепланировка Шпатлевка стен штукатурка покраска укладка декеративного кирпича Поклейка обоев всех видов Укладка линолеума паркетной доски ковролина ламината кварц винил Стяжка пола наливные полы установка плинтусов Декоративные штукатурки краски Ремонт ванных комнат санузлов под ключ Электромонтажные и сантехнические работы Оплата работ по факту выполнения поэтапно Скидки магазина до
shouldSplit: True | pipeline_prediction: False
--------------------------------------------------------------------------------
Описание: делаем капитальный внутренний ремонт а также мелкий бытовой електрика сантехника плитка ламинат а также др виды работ
shouldSplit: True | pipeline_prediction: True
--------------------------------------------------------------------------------

In [10]:
from common.paths import get_avito_gitignore_data_dpath
import pandas as pd

annoted_fpath = get_avito_gitignore_data_dpath() / "20260408_191949.json"
annoted_df = pd.read_json(annoted_fpath)

mc_map_fpath = data_dpath / "rnc_mic_key_phrases.csv"
mc_map_df = pd.read_csv(mc_map_fpath)

mc_map = {
    row["mcId"]: row["mcTitle"]
    for _, row in mc_map_df.iterrows()
}

import ast
annoted_df["targetSplitMcIds"] = annoted_df["targetSplitMcIds"].apply(ast.literal_eval)
annoted_df["targetSplitMcTitles"] = annoted_df["targetSplitMcIds"].apply(lambda mc_ids: [mc_map[mc_id] for mc_id in mc_ids])

annoted_df.head()

,itemId,sourceMcId,sourceMcTitle,description,targetDetectedMcIds,targetSplitMcIds,shouldSplit,targetSplitMcTitles
0,1000001,101,Ремонт квартир и домов под ключ,"Всё виды строительных работ\r\nКачественно, в ...",[],[],False,[]
1,1000002,101,Ремонт квартир и домов под ключ,Профессионально и качественно сделаем ремонт к...,[],[],False,[]
2,1000003,101,Ремонт квартир и домов под ключ,"ремонт квартир, ванной комнате , балкон",[],[],False,[]
3,1000004,101,Ремонт квартир и домов под ключ,ЗBОНИТЕ KОHСУЛЬТАЦИЯ БЕCПЛАTНAЯ ПO ТУЛЬСKOЙ ОБ...,[],[],False,[]
4,1000005,101,Ремонт квартир и домов под ключ,Ремонт квартир любой сложности. Квартиры под к...,[],[],True,[]

In [11]:
from avito.should_split.retrieval import ChromaRetriever, VectorDbConfig, EncoderConfig

vdb_cfg = VectorDbConfig(
    collection_name="avito_descriptions",
    persist=True,
)

encoder_cfg = EncoderConfig(
    model_name="sergeyzh/rubert-mini-frida"
)

retriever = ChromaRetriever(
    examples_df=annoted_df,
    vector_db_config=vdb_cfg,
    encoder_config=encoder_cfg
)

Default prompt name is set to 'Classification'. This prompt will be applied to all `encode()` calls, except if `encode()` is called with `prompt` or `prompt_name` parameters.

In [12]:
from avito.should_split.catalog import load_microcategory_catalog
from avito.should_split.config import ShouldSplitGraphConfig
from avito.should_split.pipeline import ShouldSplitPipeline
from common.paths import get_avito_data_dpath

cfg = ShouldSplitGraphConfig.from_default_yaml()

data_dpath = get_avito_data_dpath()

mc_map_fpath = data_dpath / cfg.data.mc_map_filename
markup_fpath = data_dpath / cfg.data.markup_filename

cfg.graph.use_rag = True
graph = ShouldSplitPipeline(
    catalog=load_microcategory_catalog(mc_map_fpath),
    retriever=retriever,
    config=cfg,
    examples_df=annoted_df
)

example_desc = annoted_df.sample(1, random_state=42)["description"].values[0]
result = graph.invoke(example_desc)
print(f"Final decision: shouldSplit={result}")

2026-04-08 20:32:50,964 - avito-should-split - INFO - [SHOULD_SPLIT] [clean] 1401 -> 1310 символов
2026-04-08 20:32:50,980 - avito-should-split - INFO - [SHOULD_SPLIT] [pre_filter] shouldSplit=True, split_markers=1, categories=0
2026-04-08 20:32:51,015 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-08 20:32:51,032 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'reasoning_effort', 'temperature']
2026-04-08 20:32:51,036 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью mistral-medium-latest, ключ 1/21
2026-04-08 20:32:51,055 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-08 20:32:51,055 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-08 20:32:51,055 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели mistral-medium-latest
2026-04-08 20:33:02,720 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-08 20:33:02,722 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-08 20:33:02,723 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели mistral-medium-latest

Final decision: shouldSplit=description='здравствуйте мы предлагаем комплексные услуги с нами ваш ремонт получится без забот выполняем ремонт квартир домов коммерческих помещений под ключ любой сложности наша локация западный обход жк самолет жк достояние жк парк победы жк архитектор бригада мастеров готовы приступить к ремонту в ближайшее время все с опытом работы выполняем любые виды отделочных и ремонтных работ от стандартных вариантов до эксклюзивного проекта работаем по дизайн проекту и без авторский надзор подберем все материалы и мебель от наших партнёров по самый выгодной цене привезём при необходимости из краснодара всегда заключаем договор фиксируем дату окончания ремонта и стоимость работ также работаем дистанционно у нас большой опыт и мы сможем организовать весь процесс ремонта от начала до конца ваши выгоды при работе с нами все отделочные работы выполняем точно в срок без задержек еженедельный фотоотчет по а арр закон о тишине и чистоту на объекте соблюдаем и поддерживаем всегда работаем по договору даем официальную гарантию на все виды работы любая форма оплаты наличная и безналичная оплата нашего труда происходит поэтапно все технические нюансы согласовываем с заказчиком еще на начальной стадии работаем без выходных и праздников позвоните с удовольствием ответим на все ваши вопросы наставник вашего проекта ксения' should_split=False pre_filter_verdict=True rag_split_verdict=False categorized_mc_ids=[] top_k_examples=[RetrievedExample(text='Здравствуйте! \nМы предлагаем комплексные услуги! \n\nС нами ваш ремонт получится без забот ✅\nВыполняем ремонт квартир, домов, коммерческих помещений под ключ любой сложности! \n\nНаша локация:\n📍Западный обход, ЖК Самолет, ЖК Достояние, ЖК Парк Победы, ЖК Архитектор \n\nБригада мастеров, готовы приступить к ремонту в ближайшее время, все с опытом работы!\n\nВыполняем любые виды отделочных и ремонтных работ от стандартных вариантов до эксклюзивного проекта, работаем по дизайн проекту и без! Авторский надзор!\n\nПодберем все материалы и мебель от наших партнёров по самый выгодной цене. \nПривезём при необходимости из Краснодара.\n\n✅ Всегда заключаем договор, фиксируем дату окончания ремонта и стоимость работ. \nТакже работаем дистанционно, у нас большой опыт и мы сможем организовать весь процесс ремонта от начала до конца! \n\nВаши выгоды при работе с нами:\n✔️ Все отделочные работы выполняем точно в срок, без задержек.\n✔️ Еженедельный фотоотчет по WhаtsАрр\n✔️ Закон о тишине и чистоту на объекте соблюдаем и поддерживаем.\n✔️ ВСЕГДА работаем по договору.\n✔️ Даем официальную гарантию на все виды работы.\n✔️ Любая форма оплаты: наличная и безналичная.\nОплата нашего труда происходит поэтапно.\n\n📌 Все технические нюансы согласовываем с заказчиком еще на начальной стадии.\n\n✅ РАБОТАЕМ БЕЗ ВЫХОДНЫХ И ПРАЗДНИКОВ!\n☎ Позвоните, с удовольствием ответим на все Ваши вопросы!\n24/7 Наставник вашего проекта 😊\n\nКсения', should_split=False, categories=[], score=0.0), RetrievedExample(text='Здравствуйте! \nМы предлагаем комплексные услуги! \n\nС нами ваш ремонт получится без забот ✅\nВыполняем ремонт квартир, домов, коммерческих помещений под ключ любой сложности! \n\nНаша локация:\n📍Западный обход, ЖК Самолет, ЖК Достояние, ЖК Парк Победы, ЖК Архитектор \n\nБригада мастеров, готовы приступить к ремонту в ближайшее время, все с опытом работы!\n\nВыполняем любые виды отделочных и ремонтных работ от стандартных вариантов до эксклюзивного проекта, работаем по дизайн проекту и без! Авторский надзор!\n\nПодберем все материалы и мебель от наших партнёров по самый выгодной цене. \nПривезём при необходимости из Краснодара.\n\n✅ Всегда заключаем договор, фиксируем дату окончания ремонта и стоимость работ. \nТакже работаем дистанционно, у нас большой опыт и мы сможем организовать весь процесс ремонта от начала до конца! \n\nВаши выгоды при работе с нами:\n✔️ Все отделочные работы выполняем точно в срок, без задержек.\n✔️ Еженедельный фотоотчет по WhаtsАрр\n✔️ Закон о тишине и чистоту на объекте соблюдаем и поддерживаем.\n✔️ ВСЕГДА работаем по договору.\n✔️ Даем официальную гарантию на все виды работы.\n✔️ Любая форма оплаты: наличная и безналичная.\nОплата нашего труда происходит поэтапно.\n\n📌 Все технические нюансы согласовываем с заказчиком еще на начальной стадии.\n\n✅ РАБОТАЕМ БЕЗ ВЫХОДНЫХ И ПРАЗДНИКОВ!\n☎ Позвоните, с удовольствием ответим на все Ваши вопросы!\n24/7 Наставник вашего проекта 😊\n\nКсения', should_split=False, categories=[], score=0.0), RetrievedExample(text='Бригада мастеров с опытом более 10 лет предоставляет все виды ремонтно-отделочных работ.Выполняем качественно и по разумным ценам , частично или полный ремонт квартир.А также : ремонт коттеджей, офисов и др.комерчиских помещений под ключ.\nНаши услуги:\n✓ Шпаклёвка стен,штукатурка,покраска,оклейка обоев.\n✓ Укладка линолеума,ковролина,ламината,установка плинтусов.\n✓ Ремонт ванных комнат/санузлов под ключ.\n✓ Электромонтажные и сантехнические работы.\nВыполняем (поэтапно).Консультация и составления сметы -бесплатно .Всю финансовую отчётность предоставляем в полном объеме.Предоставим договор .Гарантия .Во всех районах города Краснодара и края .\nПольльзуйтесь услугами профессионалов.Реальным клиентам предоставляются скидки !', should_split=False, categories=[], score=0.0)] drafts=[] stage_durations_sec={'clean': 0.001585599995451048, 'pre_filter': 0.0029424999956972897, 'rag_split': 11.741012599988608, 'llm_exit': 3.00002284348011e-07} metadata={'triggered_mc_ids': [], 'split_marker_count': 1, 'should_split_prompt_mode': 'rag', 'llm_response': 'False'}

False