In [1]:
from common.paths import get_avito_data_dpath
from common.logger import AVITO_SHOULD_SPLIT_LOGGER as logger

import pandas as pd
import numpy as np

In [2]:
data_fpath = get_avito_data_dpath() / "rnc_dataset_markup.json"
id_cat_map_fpath = get_avito_data_dpath() / "rnc_mic_key_phrases.csv"

data_df = pd.read_json(data_fpath)
id_cat_map_df = pd.read_csv(id_cat_map_fpath)

id_cat_map = dict(zip(id_cat_map_df["mcId"], id_cat_map_df["mcTitle"]))
print(id_cat_map)
data_df.head()

{101: 'Ремонт квартир и домов под ключ', 102: 'Сантехника', 103: 'Электрика', 104: 'Натяжные потолки', 105: 'Укладка плитки', 106: 'Поклейка обоев', 107: 'Малярные работы', 108: 'Штукатурные работы', 109: 'Напольные покрытия', 110: 'Гипсокартон', 111: 'Демонтажные работы'}

,itemId,sourceMcId,sourceMcTitle,description,targetDetectedMcIds,targetSplitMcIds,shouldSplit,caseType,split
0,1000001,101,Ремонт квартир и домов под ключ,"Всё виды строительных работ\r\nКачественно, в ...",[],[],False,no_other_microcategories_detected,NaN
1,1000002,101,Ремонт квартир и домов под ключ,Профессионально и качественно сделаем ремонт к...,"[102, 103, 105, 108, 109, 110]",[],False,other_microcategories_detected_but_not_split,NaN
2,1000003,101,Ремонт квартир и домов под ключ,"ремонт квартир, ванной комнате , балкон",[102],[],False,other_microcategories_detected_but_not_split,NaN
3,1000004,101,Ремонт квартир и домов под ключ,ЗBОНИТЕ KОHСУЛЬТАЦИЯ БЕCПЛАTНAЯ ПO ТУЛЬСKOЙ ОБ...,"[102, 103, 104, 105, 106, 107, 108, 109, 110]","[102, 103, 104, 105, 106, 107, 108, 109, 110]",True,split,NaN
4,1000005,101,Ремонт квартир и домов под ключ,Ремонт квартир любой сложности. Квартиры под к...,[],[],False,no_other_microcategories_detected,NaN

In [3]:
from avito.features import extract_should_split_features

X = extract_should_split_features(data_df)
y = data_df["shouldSplit"].values
assert len(X) == len(y)
logger.info(f"Размер X: {X.shape}, размер y: {y.shape}")
X.head()

2026-04-07 23:26:41,061 - avito-should-split - INFO - [SHOULD_SPLIT] Размер X: (2480, 21), размер y: (2480,)

,description_word_count,description_char_count,split_marker_count,complex_marker_count,marker_ratio,has_bullets,sentence_count,avg_word_len,punctuation_ratio,max_keyphrase_rapidfuzz_mc_101,...,max_keyphrase_rapidfuzz_mc_103,max_keyphrase_rapidfuzz_mc_104,max_keyphrase_rapidfuzz_mc_105,max_keyphrase_rapidfuzz_mc_106,max_keyphrase_rapidfuzz_mc_107,max_keyphrase_rapidfuzz_mc_108,max_keyphrase_rapidfuzz_mc_109,max_keyphrase_rapidfuzz_mc_110,max_keyphrase_rapidfuzz_mc_111,split_marker_near_keyphrase
0,13.0,85.0,0.0,0.0,0.0,0,2.0,5.384615,0.023529,52.380951,...,34.482758,36.799999,30.357143,33.333332,32.758621,33.928570,28.318584,33.043480,33.027523,0
1,107.0,803.0,0.0,3.0,0.0,0,18.0,6.222222,0.029888,100.000000,...,75.000000,66.666664,81.250000,76.190475,66.666664,62.068966,100.000000,57.142857,68.965515,0
2,6.0,39.0,0.0,0.0,0.0,0,1.0,6.400000,0.051282,74.285713,...,54.545456,58.333332,57.142857,66.666664,48.387096,52.173912,70.588234,50.000000,55.882355,0
3,169.0,1247.0,0.0,0.0,0.0,0,10.0,6.193750,0.034483,6.451613,...,5.008945,6.366048,5.008945,72.727272,4.817128,4.834378,4.472272,60.869564,4.834378,0
4,26.0,181.0,0.0,1.0,0.0,0,6.0,5.692307,0.044199,69.565216,...,61.538460,48.484848,48.484848,76.190475,66.666664,27.272728,48.484848,57.142857,48.484848,0

In [13]:
from avito.embeddings import SentenceTransformerEncoder, EncoderConfig

encoder = SentenceTransformerEncoder(EncoderConfig.from_default_yaml())

def build_text_to_encode(row):
    return f"""{row['description']}"""

texts_to_encode = data_df.apply(build_text_to_encode, axis=1).tolist()
text_embeddings = encoder.encode(texts_to_encode)
X = np.hstack([X.values, text_embeddings])

2026-04-07 23:18:54,167 - avito-embeddings - INFO - [AVITO/EMBEDDINGS] Пробую загрузить локальную модель: C:\Users\User\Desktop\dirs\Dev\hack-mfti\avito\checkpoints\rubert-mini-frida
Default prompt name is set to 'Classification'. This prompt will be applied to all `encode()` calls, except if `encode()` is called with `prompt` or `prompt_name` parameters.
2026-04-07 23:18:54,308 - avito-embeddings - INFO - [AVITO/EMBEDDINGS] Запуск encode для 2480 текстов

Batches:   0%|          | 0/78 [00:00<?, ?it/s]

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train, sample_weight=1000000)

RandomForestClassifier(random_state=42)

In [27]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = model.predict(X_test)
report = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print(report)
cm

              precision    recall  f1-score   support

       False       0.82      0.99      0.89       403
        True       0.44      0.04      0.08        93

    accuracy                           0.81       496
   macro avg       0.63      0.52      0.49       496
weighted avg       0.75      0.81      0.74       496

array([[398,   5],
       [ 89,   4]])

In [21]:
def build_few_shots():
    random_ids = data_df.sample(5, random_state=42).index.tolist()
    few_shots = []
    for idx in random_ids:
        row = data_df.loc[idx]
        few_shots.append(f"""Описание: {row['description']}
Ответ: {row['shouldSplit']}""")
    return "\n".join(few_shots)

instruction_prompt = f"""
Ты — эксперт по классификации объявлений об услугах на платформе Авито.

Тебе даётся описание объявления, опубликованного в категории «Ремонт квартир и домов под ключ».
Твоя задача — определить, упоминает ли селлер какие-либо услуги, которые он готов выполнять ОТДЕЛЬНО, вне комплексного ремонта.

КРИТЕРИИ для ответа True (нужно разделить):
- Селлер явно предлагает отдельные услуги: «также делаем электрику», «сантехнику выполняем отдельно»
- Есть перечисление самостоятельных работ с ценами или условиями для каждой
- Используются фразы: «отдельно», «также выполняем», «помимо основного», «принимаем заказы на»

КРИТЕРИИ для ответа False (не нужно разделять):
- Услуги упомянуты только как составляющие комплексного ремонта: «ремонт под ключ, включая электрику и сантехнику»
- Перечисление видов работ без явного предложения их по отдельности
- Краткое общее описание без конкретики по отдельным услугам

ФОРМАТ ОТВЕТА:
Строго одна строка: True или False
Пример: True
Пример: False

ПРИМЕРЫ:
{build_few_shots()}
"""
print(instruction_prompt)

from common.mistral import call_mistral, MistralCallConfig

def build_messages(row):
    return [
        {"role": "system", "content": instruction_prompt},
        {"role": "user", "content": f"Описание: {row['description']}"},
    ]

cfg = MistralCallConfig(
    models_list=["ministral-14b-latest"]
)

from tqdm.auto import tqdm

mistral_predictions = []
subsample_df = data_df.sample(20, random_state=43)

for _, row in tqdm(subsample_df.iterrows(), total=len(subsample_df)):
    messages = build_messages(row)
    response = call_mistral(cfg, messages=messages, temperature=0.0)
    mistral_predictions.append(response)

mistral_predictions

Ты — эксперт по классификации объявлений об услугах на платформе Авито.

Тебе даётся описание объявления, опубликованного в категории «Ремонт квартир и домов под ключ».
Твоя задача — определить, упоминает ли селлер какие-либо услуги, которые он готов выполнять ОТДЕЛЬНО, вне комплексного ремонта.

КРИТЕРИИ для ответа True (нужно разделить):
- Селлер явно предлагает отдельные услуги: «также делаем электрику», «сантехнику выполняем отдельно»
- Есть перечисление самостоятельных работ с ценами или условиями для каждой
- Используются фразы: «отдельно», «также выполняем», «помимо основного», «принимаем заказы на»

КРИТЕРИИ для ответа False (не нужно разделять):
- Услуги упомянуты только как составляющие комплексного ремонта: «ремонт под ключ, включая электрику и сантехнику»
- Перечисление видов работ без явного предложения их по отдельности
- Краткое общее описание без конкретики по отдельным услугам

ФОРМАТ ОТВЕТА:
Строго одна строка: True или False
Пример: True
Пример: False

ПРИМЕРЫ:
Описание: Здравствуйте!
Мы предлагаем комплексные услуги!

С нами ваш ремонт получится без забот ✅
Выполняем ремонт квартир, домов, коммерческих помещений под ключ любой сложности!

Наша локация:
📍Западный обход, ЖК Самолет, ЖК Достояние, ЖК Парк Победы, ЖК Архитектор

Бригада мастеров, готовы приступить к ремонту в ближайшее время, все с опытом работы!

Выполняем любые виды отделочных и ремонтных работ от стандартных вариантов до эксклюзивного проекта, работаем по дизайн проекту и без! Авторский надзор!

Подберем все материалы и мебель от наших партнёров по самый выгодной цене.
Привезём при необходимости из Краснодара.

✅ Всегда заключаем договор, фиксируем дату окончания ремонта и стоимость работ.
Также работаем дистанционно, у нас большой опыт и мы сможем организовать весь процесс ремонта от начала до конца!

Ваши выгоды при работе с нами:
✔️ Все отделочные работы выполняем точно в срок, без задержек.
✔️ Еженедельный фотоотчет по WhаtsАрр
✔️ Закон о тишине и чистоту на объекте соблюдаем и поддерживаем.
✔️ ВСЕГДА работаем по договору.
✔️ Даем официальную гарантию на все виды работы.
✔️ Любая форма оплаты: наличная и безналичная.
Оплата нашего труда происходит поэтапно.

📌 Все технические нюансы согласовываем с заказчиком еще на начальной стадии.

✅ РАБОТАЕМ БЕЗ ВЫХОДНЫХ И ПРАЗДНИКОВ!
☎ Позвоните, с удовольствием ответим на все Ваши вопросы!
24/7 Наставник вашего проекта 😊

Ксения
Ответ: False
Описание: Выполним любые ремонтно- строительные работы.Шпаклевка,штукатурка,гипсокартон, Армстронг, покраска,кафель, ламинат,обои.Очень ответственно,качественно,как для себя!Обращайтесь!
Ответ: False
Описание: Мы выполняем отделочные и ремонтные работы любой сложности, работаем со многими материалами. Ремонт квартир от самого простого """косметического"" до сложно """элитного""" ремонта.
Консультация и замер бесплатно. Адекватные цены.Оплата наличный/безналичный расчёт.Опытные мастер. Быстрый приезд.
Ответ: False
Описание: строительные работы.
Ответ: False
Описание: ► Пoчeму вы можете довepить ремонт нам:

► Дoгoвоp на всe pаботы.

► Реaльнaя гaрaнтия дo 2 лет.

► Фиксиpованная цена на протяжении всего ремонта.

► Фото и видео отчеты ежедневно.

► Скидки на материалы.

► Соблюдение сроков всех работ.

► Мы готовы приехать на замер в день обращения.

► Соблюдение всех норм и стандартов.

► Уборка мусора и пыли вовремя и после ремонта.

► Профессиональные мастера с опытом работ от 15 лет.

► Оплата работ поэтапно.

► Наличный и безналичный расчёт.

Добpый дeнь!

Cпаcибo зa интерес к нaшим услугaм. Мы пpедлагаeм качествeнный peмoнт "пoд ключ", с договоpoм, гарантиeй и aдeквaтными цeнами.

Мы можем показать Вам свои объекты: готовые или в работе.

Рады, что имеем возможность поделиться с вами своим опытом и на деле поддержать вас в ремонте вашей квартиры.

Звоните в любое время, я с удовольствием отвечу на все вопросы!
Ответ: False

  0%|          | 0/20 [00:00<?, ?it/s]

2026-04-07 23:40:49,168 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:49,170 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:49,172 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:49,196 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:49,199 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:49,201 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:49,634 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:49,636 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:49,638 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:49,640 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:49,642 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:49,645 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:49,668 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:49,670 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:49,672 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:50,001 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:50,004 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:50,005 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:50,008 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:50,009 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:50,012 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:50,034 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:50,035 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:50,038 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:50,513 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:50,516 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:50,517 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:50,519 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:50,521 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:50,523 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:50,549 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:50,550 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:50,552 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:51,126 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:51,128 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:51,129 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:51,131 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:51,133 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:51,136 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:51,158 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:51,160 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:51,162 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:51,613 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:51,615 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:51,617 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:51,619 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:51,621 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:51,623 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:51,646 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:51,648 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:51,650 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:52,014 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:52,016 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:52,017 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:52,019 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:52,021 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:52,024 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:52,045 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:52,047 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:52,049 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:52,457 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:52,460 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:52,461 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:52,463 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:52,465 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:52,468 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:52,489 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:52,491 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:52,493 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:52,841 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:40:52,842 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:52,844 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:52,846 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:52,848 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:52,851 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:52,893 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:52,894 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:52,896 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:53,345 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:40:53,347 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:53,349 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:53,352 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:53,353 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:53,357 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:53,380 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:53,382 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:53,384 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:53,740 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:53,742 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:53,743 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:53,747 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:53,749 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:53,753 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:53,780 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:53,783 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:53,785 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:54,198 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:40:54,200 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:54,202 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:54,204 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:54,206 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:54,207 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:54,230 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:54,232 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:54,234 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:54,584 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:54,586 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:54,587 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:54,589 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:54,591 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:54,593 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:54,615 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:54,617 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:54,618 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:54,974 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:40:54,975 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:54,977 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:54,979 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:54,980 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:54,983 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:55,003 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:55,005 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:55,007 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:55,470 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:55,472 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:55,474 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:55,476 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:55,478 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:55,480 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:55,502 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:55,503 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:55,505 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:56,150 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:40:56,151 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:56,153 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:56,155 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:56,156 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:56,159 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:56,181 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:56,189 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:56,191 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:56,630 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:40:56,632 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:56,633 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:56,635 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:56,637 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:56,640 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:56,659 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:56,661 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:56,663 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:57,069 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:57,071 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:57,072 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:57,074 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:57,077 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:57,079 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:57,100 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:57,101 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:57,103 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:57,507 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:57,510 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:57,511 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:57,513 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:57,514 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:57,517 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:57,538 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:57,539 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:57,541 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:58,493 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:40:58,495 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:58,496 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:40:58,498 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:40:58,500 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:40:58,502 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:40:58,524 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:40:58,529 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:40:58,532 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:40:59,102 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:40:59,104 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:40:59,106 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest

['False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True']

In [22]:
subsample_df["mistral_prediction"] = mistral_predictions
subsample_df[["description", "shouldSplit", "mistral_prediction"]]

,description,shouldSplit,mistral_prediction
1230,"Профессиональный ремонт квартир, коттеджей и о...",False,False
793,все виды отделки,False,False
956,Ремонт квартир и домов под ключ по договору с ...,False,False
261,Бригада из двух человек с опытом работы по отд...,False,False
896,"KОMПЛЕКСНЫЙ pемонт квартиp ""с нуля""!\nСпециали...",False,False
2141,Сделаю всё качественно и аккуратно. Опыт работ...,False,False
269,РемонтСервис64💪\nНА ФОТО НАШИ РЕАЛЬНЫЕ РАБОТЫ!...,False,False
1580,"Ремонт, отделка, кафель, электропроводка, тёпл...",False,True
1601,"ОТКОСЫ ПЛАСТИКОВЫЕ, ЛАМИНИРОВАННЫЕ. Простыe, п...",False,True
1533,Выполним качественный ремонт вашей квартиры и ...,False,False
916,Ремонт квартир под ключ с гарантией. \nВыполня...,False,True
163,Качественный ремонт и отделка квартир и домов ...,False,False
1716,Ванна под ключ. Качественная укладка керамичес...,False,True
1015,Нет уверенности в качестве строительных работ ...,False,False
2428,ВНУТРЕННЯЯ ОТДЕЛКА ПОМЕЩЕНИЙ ОТДЕЛОЧНИКИ В НО...,False,True
745,Привет всем посетителям моего объявления! Скаж...,True,True
1167,"Ремонт квартиры, офисы ,",False,False
1004,Выполняю спектр услуг по ремонту помещений. Ма...,False,False
2223,РЕМОНТ КВАРТИР В СОЧИ/АДЛЕР B КPАТЧАЙШИE CРOKИ...,False,False
2159,Выполняем работы! \r\nОтделочные \r\nШтукатурк...,False,True

In [24]:
from sklearn.model_selection import train_test_split

_, stratified_test_df = train_test_split(data_df, test_size=0.2, random_state=42, stratify=data_df["shouldSplit"])
stratified_test_df = stratified_test_df.sample(100, random_state=43)

In [25]:
stratified_test_df["mistral_prediction"] = None
for idx, row in tqdm(stratified_test_df.iterrows(), total=len(stratified_test_df)):
    messages = build_messages(row)
    response = call_mistral(cfg, messages=messages, temperature=0.0)
    stratified_test_df.at[idx, "mistral_prediction"] = response

  0%|          | 0/100 [00:00<?, ?it/s]

2026-04-07 23:42:19,736 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:19,736 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:19,736 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:19,767 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:19,767 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:19,771 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:20,099 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:20,100 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:20,102 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:20,105 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:20,107 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:20,110 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:20,132 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:20,134 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:20,137 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:20,536 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:42:20,539 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:20,540 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:20,549 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:20,552 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:20,554 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:20,579 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:20,581 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:20,584 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:21,174 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:42:21,176 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:21,178 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:21,181 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:21,183 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:21,183 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:21,208 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:21,209 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:21,213 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:21,654 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:21,657 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:21,660 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:21,664 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:21,664 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:21,668 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:21,691 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:21,693 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:21,695 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:23,113 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:42:23,113 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:23,113 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:23,120 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:23,121 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:23,124 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:23,146 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:23,148 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:23,150 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:23,737 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:42:23,739 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:23,740 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:23,742 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:23,744 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:23,747 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:23,770 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:23,772 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:23,774 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:24,260 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:42:24,261 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:24,262 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:24,265 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:24,266 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:24,269 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:24,292 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:24,294 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:24,298 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:24,650 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:24,652 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:24,653 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:24,656 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:24,657 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:24,659 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:24,681 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:24,683 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:24,685 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:25,098 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:25,099 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:25,101 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:25,103 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:25,104 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:25,107 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:25,127 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:25,134 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:25,136 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:25,487 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:25,490 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:25,491 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:25,493 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:25,495 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:25,498 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:25,518 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:25,520 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:25,521 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:25,943 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:25,945 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:25,947 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:25,949 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:25,951 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:25,953 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:25,973 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:25,976 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:25,979 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:26,398 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:26,399 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:26,401 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:26,403 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:26,404 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:26,407 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:26,428 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:26,430 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:26,432 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:26,882 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:42:26,883 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:26,883 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:26,889 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:26,890 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:26,890 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:26,928 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:26,928 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:26,928 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:27,490 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 4 символов
2026-04-07 23:42:27,492 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:27,493 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:27,496 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:27,498 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:27,500 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:27,512 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:27,512 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:27,512 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:27,929 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:27,931 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:27,933 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:27,935 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:27,936 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:27,938 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:27,960 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:27,962 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:27,963 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:28,383 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:28,385 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:28,386 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:28,388 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:28,389 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:28,392 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:28,412 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:28,413 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:28,415 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:28,824 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:28,825 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:28,827 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:28,829 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:28,831 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:28,833 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:28,853 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:28,858 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:28,860 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:29,376 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:29,378 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:29,380 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:29,382 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:29,384 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:29,387 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:29,407 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:29,409 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:29,411 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:30,026 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:30,028 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:30,029 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:30,031 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:30,033 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:30,035 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:30,056 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:30,057 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:30,060 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest
2026-04-07 23:42:31,104 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: получен ответ длиной 5 символов
2026-04-07 23:42:31,106 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: успешное выполнение на попытке 1
2026-04-07 23:42:31,108 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: успешный вызов модели ministral-14b-latest
2026-04-07 23:42:31,110 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: начало вызова API
2026-04-07 23:42:31,112 - mistral-call - DEBUG - [MISTRAL 🇫🇷] call_mistral: параметры - ['messages', 'temperature']
2026-04-07 23:42:31,114 - mistral-call - INFO - [MISTRAL 🇫🇷] call_mistral: попытка 1/1 с моделью ministral-14b-latest, ключ 2/21
2026-04-07 23:42:31,143 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: вызов функции с timeout=240
2026-04-07 23:42:31,145 - mistral-call - DEBUG - [MISTRAL 🇫🇷] safe_call: попытка 1
2026-04-07 23:42:31,148 - mistral-call - DEBUG - [MISTRAL 🇫🇷] sub_call: попытка вызова модели ministral-14b-latest